In [47]:
#### Implementation of Banker's Algorithm
# Necessary header Files
import numpy as np

# call bankars algorithm using user-defined function
def BankarAlgorithm(P,PR_Allocation,PR_Max,R_Availabel):
    PR_Allocation_Matrix = np.array(PR_Allocation)
    PR_Max_Matrix = np.array(PR_Max)
    PR_Need_Matrix = PR_Max_Matrix - PR_Allocation_Matrix
    print('Currently Allocated Resources are :\n', PR_Allocation_Matrix)
    print('Maximum Resources Required :\n', PR_Max_Matrix)
    print('Resources Required to Executed the Processes:\n', PR_Need_Matrix)
    R_Availabel_Matrix = np.array(R_Availabel)
    print('Avaliable Resourcess are:\n', R_Availabel_Matrix)
    TotalProcess = len(P)
    safeProcess = []
    ReadyProcess = np.zeros(TotalProcess)
   # print(ReadyProcess)
    Count = 0
    while(Count<TotalProcess):
        Flag = 0
        for i in range(TotalProcess):
            if ReadyProcess[i] == 0 and np.min(np.greater_equal(R_Availabel_Matrix,PR_Need_Matrix[i,:])):
                R_Availabel_Matrix += PR_Allocation_Matrix[i,:]
                print('Currently Executed Process:', P[i])
                print('After Execution of Processes', P[i], ', Avalible resources are: \n', R_Availabel_Matrix)
                safeProcess.append(P[i])
                ReadyProcess[i] = 1
                Flag = 1
                Count += 1
        if Flag == 0:
            break
    print('\n************************** Output *******************************')
    if Count<TotalProcess:
        print('Deadlock Occur')
        print('Rest of the Safe Processes:\n',safeProcess)
    else:
        print('System is Safe')
        print('Safe Processe Order:\n',safeProcess)
        
        
# Initial Parameters
P = ['P1','P2','P3','P4','P5']
R = ['A','B','C']
PR_Allocation = [[0,1,0],[2,0,0],[3,0,2],[2,1,1],[0,0,2]]
PR_Max = [[7,5,3],[3,2,2],[9,0,2],[2,2,2],[4,3,3]]
R_Availabel = [3,3,2]

# Call the Function through Parameters
BankarAlgorithm(P,PR_Allocation,PR_Max,R_Availabel)

Currently Allocated Resources are :
 [[0 1 0]
 [2 0 0]
 [3 0 2]
 [2 1 1]
 [0 0 2]]
Maximum Resources Required :
 [[7 5 3]
 [3 2 2]
 [9 0 2]
 [2 2 2]
 [4 3 3]]
Resources Required to Executed the Processes:
 [[7 4 3]
 [1 2 2]
 [6 0 0]
 [0 1 1]
 [4 3 1]]
Avaliable Resourcess are:
 [3 3 2]
Currently Executed Process: P2
After Execution of Processes P2 , Avalible resources are: 
 [5 3 2]
Currently Executed Process: P4
After Execution of Processes P4 , Avalible resources are: 
 [7 4 3]
Currently Executed Process: P5
After Execution of Processes P5 , Avalible resources are: 
 [7 4 5]
Currently Executed Process: P1
After Execution of Processes P1 , Avalible resources are: 
 [7 5 5]
Currently Executed Process: P3
After Execution of Processes P3 , Avalible resources are: 
 [10  5  7]

************************** Output *******************************
System is Safe
Safe Processe Order:
 ['P2', 'P4', 'P5', 'P1', 'P3']
